import type { Distractor, LevelDef, Vec, Wall } from './types';

/**
 * Logical playfield: 360 x 640 (portrait phone units).
 * Scaled to the real screen at render time. Y grows downward.
 */
const W = 360;
const H = 640;

function bounds(): Wall[] {
  return [
    { id: 'floor', x: 0, y: H - 20, w: W, h: 20 },
    { id: 'ceil', x: 0, y: 0, w: W, h: 16 },
    { id: 'left', x: 0, y: 0, w: 16, h: H },
    { id: 'right', x: W - 16, y: 0, w: 16, h: H },
  ];
}

function wall(id: string, x: number, y: number, w: number, h: number, extra?: Partial<Wall>): Wall {
  return { id, x, y, w, h, ...extra };
}

function lvl(
  partial: Omit<LevelDef, 'width' | 'height' | 'playerRadius' | 'goalRadius'> & {
    goalRadius?: number;
    playerRadius?: number;
  },
): LevelDef {
  return {
    width: W,
    height: H,
    playerRadius: partial.playerRadius ?? 14,
    goalRadius: partial.goalRadius ?? 22,
    ...partial,
  };
}

/** Train doors that start shut (from) and slide open (to). */
function doorPair(
  id: string,
  y: number,
  holeX: number,
  holeW: number,
  periodMs: number,
  phaseMs = 0,
  thickness = 24,
): Wall[] {
  const half = holeW / 2;
  const move = (fromX: number, toX: number) => ({
    from: { x: fromX, y },
    to: { x: toX, y },
    periodMs,
    mode: 'snap' as const,
    phaseMs,
  });
  return [
    {
      id: `${id}-L`,
      x: holeX,
      y,
      w: half,
      h: thickness,
      kind: 'door',
      label: 'DOOR',
      move: move(holeX, holeX - half),
    },
    {
      id: `${id}-R`,
      x: holeX + half,
      y,
      w: half,
      h: thickness,
      kind: 'door',
      move: move(holeX + half, holeX + holeW),
    },
  ];
}

function lintel(id: string, y: number, holeX: number, holeW: number, thickness = 24): Wall[] {
  const right = holeX + holeW;
  return [
    wall(`${id}-l`, 16, y, Math.max(0, holeX - 16), thickness),
    wall(`${id}-r`, right, y, Math.max(0, W - 16 - right), thickness),
  ];
}

function ping(
  id: string,
  text: string,
  delayMs: number,
  impulse: Vec,
  x: number,
  y: number,
): Distractor {
  return { id, text, delayMs, durationMs: 1700, impulse, x, y };
}

const shelf = (id: string, y: number, gapX: number, gapW: number, thickness = 18) =>
  lintel(id, y, gapX, gapW, thickness);

const CAMPAIGN: LevelDef[] = [
  lvl({
    id: 1,
    chapter: 'morning',
    name: 'Badge In',
    tagline: 'Drag, release, ricochet. The capsule is the whole job.',
    mechanics: ['Aim'],
    start: { x: 72, y: 548 },
    goal: { x: 286, y: 96 },
    maxBounces: 10,
    walls: [
      ...bounds(),
      wall('desk', 36, 300, 78, 18),
      wall('badge-gate', 150, 430, 18, 90),
    ],
  }),
  lvl({
    id: 2,
    chapter: 'morning',
    name: 'Partition Bounce',
    tagline: 'The partition is just a wall with a cost center.',
    mechanics: ['Walls'],
    start: { x: 78, y: 250 },
    goal: { x: 278, y: 168 },
    goalRadius: 24,
    maxBounces: 12,
    walls: [
      ...bounds(),
      wall('divider', 168, 16, 20, 430),
      wall('low-desk', 200, 500, 110, 16),
    ],
  }),
  lvl({
    id: 3,
    chapter: 'morning',
    name: 'Elevator Pitch',
    tagline: 'The shaft is safe. Step in and let it lift you.',
    mechanics: ['Elevator'],
    start: { x: 250, y: 572 },
    goal: { x: 250, y: 58 },
    maxBounces: 12,
    walls: [
      ...bounds(),
      wall('shaft-l', 196, 36, 16, 470),
      wall('shaft-r', 300, 36, 16, 470),
      wall('lobby', 16, 430, 180, 18),
    ],
    zones: [
      {
        id: 'elev',
        kind: 'shaft',
        x: 212,
        y: 40,
        w: 88,
        h: 500,
        speed: 700,
        label: 'ELEV',
      },
    ],
  }),
  lvl({
    id: 0,
    chapter: 'morning',
    name: 'Stairwell Bounce',
    tagline: 'Three landings, three gaps. Climb them with a ricochet.',
    mechanics: ['Walls'],
    start: { x: 180, y: 560 },
    goal: { x: 270, y: 78 },
    maxBounces: 16,
    walls: [
      ...bounds(),
      ...shelf('land-a', 160, 200, 130),
      ...shelf('land-b', 330, 24, 140),
      ...shelf('land-c', 480, 190, 140),
    ],
  }),
  lvl({
    id: 0,
    chapter: 'morning',
    name: 'Copy Room',
    tagline: 'The green pad is the copier. It gives the bounce back.',
    mechanics: ['Boost pad'],
    start: { x: 70, y: 530 },
    goal: { x: 292, y: 88 },
    maxBounces: 14,
    walls: [
      ...bounds(),
      wall('boost', 36, 468, 90, 16, { kind: 'pad', boost: 1.42, label: 'BOOST' }),
      wall('rack', 150, 170, 18, 210),
      wall('out-tray', 210, 400, 110, 16),
    ],
  }),
  lvl({
    id: 0,
    chapter: 'morning',
    name: 'Service Elevator',
    tagline: 'Freight elevator, same rule. Step in. It lifts you.',
    mechanics: ['Elevator'],
    start: { x: 92, y: 568 },
    goal: { x: 92, y: 64 },
    maxBounces: 12,
    walls: [
      ...bounds(),
      wall('shaft-l', 40, 28, 16, 520),
      wall('shaft-r', 148, 28, 16, 520),
      wall('loading', 164, 360, 180, 18),
    ],
    zones: [
      {
        id: 'freight',
        kind: 'shaft',
        x: 56,
        y: 36,
        w: 92,
        h: 540,
        speed: 680,
        label: 'ELEV',
      },
    ],
  }),
  lvl({
    id: 4,
    chapter: 'commute',
    name: 'Closing Doors',
    tagline: 'Wait for the gap, then bounce straight through.',
    mechanics: ['Train doors'],
    start: { x: 180, y: 560 },
    goal: { x: 180, y: 78 },
    maxBounces: 14,
    walls: [
      ...bounds(),
      ...lintel('gate', 300, 136, 88),
      ...doorPair('gate', 300, 136, 88, 2600),
    ],
  }),
  lvl({
    id: 5,
    chapter: 'commute',
    name: 'Rush Hour',
    tagline: 'Two gates. One opening. You only need the overlap.',
    mechanics: ['Train doors'],
    start: { x: 180, y: 568 },
    goal: { x: 180, y: 72 },
    maxBounces: 16,
    walls: [
      ...bounds(),
      ...lintel('low', 430, 132, 96),
      ...doorPair('low', 430, 132, 96, 2800, 0),
      ...lintel('high', 250, 132, 96),
      ...doorPair('high', 250, 132, 96, 2800, 400),
      wall('crowd', 40, 510, 78, 14, {
        kind: 'moving',
        move: {
          from: { x: 24, y: 510 },
          to: { x: 250, y: 510 },
          periodMs: 3400,
          mode: 'cosine',
        },
      }),
    ],
  }),
  lvl({
    id: 6,
    chapter: 'commute',
    name: 'Moving Walkway',
    tagline: 'Let the belt do the commuting. The elevator finishes it.',
    mechanics: ['Walkway', 'Elevator'],
    start: { x: 70, y: 560 },
    goal: { x: 294, y: 68 },
    maxBounces: 14,
    walls: [
      ...bounds(),
      wall('station', 16, 16, 236, 484),
      wall('shaft-l', 252, 16, 16, 484),
      wall('shaft-r', 328, 16, 16, 560),
    ],
    zones: [
      {
        id: 'walk',
        kind: 'belt',
        x: 24,
        y: 512,
        w: 230,
        h: 96,
        dir: { x: 1, y: 0 },
        speed: 460,
        label: 'WALK',
      },
      {
        id: 'up',
        kind: 'shaft',
        x: 268,
        y: 36,
        w: 60,
        h: 560,
        speed: 720,
        label: 'ELEV',
      },
    ],
  }),
  lvl({
    id: 0,
    chapter: 'commute',
    name: 'Local Stop',
    tagline: 'One wide pair of doors. Wait, then go straight up.',
    mechanics: ['Train doors'],
    start: { x: 180, y: 552 },
    goal: { x: 180, y: 72 },
    maxBounces: 14,
    walls: [
      ...bounds(),
      ...lintel('local', 280, 110, 140),
      ...doorPair('local', 280, 110, 140, 2600),
    ],
  }),
  lvl({
    id: 0,
    chapter: 'commute',
    name: 'Express Belt',
    tagline: 'The walkway runs you to the uptown car.',
    mechanics: ['Walkway', 'Elevator'],
    start: { x: 64, y: 548 },
    goal: { x: 300, y: 70 },
    maxBounces: 14,
    walls: [
      ...bounds(),
      wall('concourse', 16, 16, 210, 470),
      wall('car-l', 258, 16, 16, 470),
      wall('car-r', 328, 16, 16, 560),
    ],
    zones: [
      {
        id: 'express',
        kind: 'belt',
        x: 24,
        y: 500,
        w: 230,
        h: 100,
        dir: { x: 1, y: 0 },
        speed: 480,
        label: 'WALK',
      },
      {
        id: 'uptown',
        kind: 'shaft',
        x: 274,
        y: 32,
        w: 54,
        h: 560,
        speed: 700,
        label: 'ELEV',
      },
    ],
  }),
  lvl({
    id: 0,
    chapter: 'commute',
    name: 'Polite Shove',
    tagline: 'The crowd bar slides. The left lane stays open.',
    mechanics: ['Moving bar'],
    start: { x: 64, y: 548 },
    goal: { x: 70, y: 78 },
    maxBounces: 14,
    walls: [
      ...bounds(),
      ...shelf('turnstile', 250, 28, 110),
      wall('crowd', 180, 400, 90, 14, {
        kind: 'moving',
        move: {
          from: { x: 160, y: 400 },
          to: { x: 250, y: 400 },
          periodMs: 3000,
          mode: 'cosine',
        },
      }),
    ],
  }),
  lvl({
    id: 7,
    chapter: 'office',
    name: 'Cubicle Grid',
    tagline: 'Cubicles cannot hold a good ricochet.',
    mechanics: ['Maze'],
    start: { x: 70, y: 575 },
    goal: { x: 286, y: 78 },
    goalRadius: 22,
    maxBounces: 16,
    walls: [
      ...bounds(),
      ...shelf('s1', 150, 230, 100),
      ...shelf('s2', 310, 30, 110),
      ...shelf('s3', 460, 210, 110),
      wall('stub', 168, 500, 16, 70),
    ],
  }),
  lvl({
    id: 8,
    chapter: 'office',
    name: 'Coffee Slick',
    tagline: 'Someone spilled the pour-over. Slide, then bank.',
    mechanics: ['Coffee slick'],
    start: { x: 64, y: 540 },
    goal: { x: 292, y: 110 },
    goalRadius: 24,
    maxBounces: 14,
    walls: [
      ...bounds(),
      wall('desk-a', 40, 250, 150, 16),
      wall('desk-b', 230, 390, 100, 16),
    ],
    zones: [
      {
        id: 'coffee',
        kind: 'slick',
        x: 48,
        y: 280,
        w: 260,
        h: 180,
        label: 'COFFEE',
      },
    ],
  }),
  lvl({
    id: 9,
    chapter: 'office',
    name: 'Open Plan',
    tagline: 'Open plan, closed corners. The green pad is a favor.',
    mechanics: ['Slick', 'Boost pad'],
    start: { x: 62, y: 560 },
    goal: { x: 292, y: 86 },
    goalRadius: 24,
    maxBounces: 16,
    walls: [
      ...bounds(),
      ...shelf('row', 200, 240, 90),
      wall('pad', 46, 450, 78, 16, { kind: 'pad', boost: 1.45, label: 'BOOST' }),
      wall('nook', 150, 330, 16, 110),
    ],
    zones: [
      {
        id: 'spill',
        kind: 'slick',
        x: 36,
        y: 470,
        w: 200,
        h: 120,
        label: 'COFFEE',
      },
    ],
  }),
  lvl({
    id: 0,
    chapter: 'office',
    name: 'Break Room',
    tagline: 'The pour-over is everywhere. Slide across it.',
    mechanics: ['Coffee slick'],
    start: { x: 80, y: 548 },
    goal: { x: 286, y: 84 },
    maxBounces: 14,
    walls: [
      ...bounds(),
      wall('counter', 30, 220, 160, 16),
      wall('fridge', 250, 360, 16, 90),
    ],
    zones: [
      {
        id: 'break-spill',
        kind: 'slick',
        x: 28,
        y: 250,
        w: 300,
        h: 220,
        label: 'COFFEE',
      },
    ],
  }),
  lvl({
    id: 0,
    chapter: 'office',
    name: 'Corner Boost',
    tagline: 'Two green pads. Use one, or both, on the way up.',
    mechanics: ['Boost pad'],
    start: { x: 64, y: 548 },
    goal: { x: 286, y: 80 },
    maxBounces: 16,
    walls: [
      ...bounds(),
      wall('pad-a', 36, 460, 80, 16, { kind: 'pad', boost: 1.4, label: 'BOOST' }),
      wall('pad-b', 230, 280, 80, 16, { kind: 'pad', boost: 1.35, label: 'BOOST' }),
      wall('file-row', 140, 180, 16, 160),
    ],
  }),
  lvl({
    id: 0,
    chapter: 'office',
    name: 'Quiet Carrel',
    tagline: 'Short partitions. A calm line still finds the capsule.',
    mechanics: ['Maze'],
    start: { x: 180, y: 560 },
    goal: { x: 180, y: 76 },
    maxBounces: 16,
    walls: [
      ...bounds(),
      wall('carrel-a', 70, 160, 16, 150),
      wall('carrel-b', 180, 300, 16, 140),
      wall('carrel-c', 270, 150, 16, 160),
      wall('desk-lip', 40, 470, 120, 16),
    ],
  }),
  lvl({
    id: 10,
    chapter: 'overtime',
    name: 'Meeting Paddle',
    tagline: 'The meeting spins. A good smack still gets you out.',
    mechanics: ['Paddle'],
    start: { x: 180, y: 560 },
    goal: { x: 180, y: 78 },
    goalRadius: 26,
    maxBounces: 18,
    walls: [...bounds(), wall('minutes', 36, 180, 70, 14), wall('minutes-r', 250, 420, 80, 14)],
    paddles: [
      {
        id: 'mtg',
        x: 180,
        y: 300,
        length: 132,
        thickness: 16,
        periodMs: 2800,
        phase: 0.4,
        boost: 1.12,
        label: 'MTG',
      },
    ],
  }),
  lvl({
    id: 11,
    chapter: 'overtime',
    name: 'Unpaid Hours',
    tagline: 'The belt feeds the meeting. The capsule is still the exit.',
    mechanics: ['Paddle', 'Walkway'],
    start: { x: 250, y: 545 },
    goal: { x: 180, y: 84 },
    goalRadius: 26,
    maxBounces: 18,
    walls: [...bounds(), ...shelf('slot', 188, 100, 170, 18), wall('inbox', 24, 340, 16, 80)],
    zones: [
      {
        id: 'desk-belt',
        kind: 'belt',
        x: 140,
        y: 488,
        w: 190,
        h: 120,
        dir: { x: -1, y: 0 },
        speed: 360,
        label: 'DESK',
      },
    ],
    paddles: [
      {
        id: 'clock',
        x: 168,
        y: 300,
        length: 108,
        thickness: 16,
        periodMs: 2500,
        phase: 1.1,
        boost: 1.14,
        label: 'MTG',
      },
    ],
  }),
  lvl({
    id: 12,
    chapter: 'overtime',
    name: 'Double Booking',
    tagline: 'Two meetings at once. Bounce through both of them.',
    mechanics: ['Paddles'],
    start: { x: 70, y: 560 },
    goal: { x: 286, y: 90 },
    goalRadius: 26,
    maxBounces: 20,
    walls: [...bounds(), wall('glass', 168, 180, 16, 160)],
    paddles: [
      {
        id: 'am',
        x: 108,
        y: 340,
        length: 110,
        thickness: 16,
        periodMs: 2600,
        phase: 0.2,
        label: 'AM',
      },
      {
        id: 'pm',
        x: 250,
        y: 260,
        length: 120,
        thickness: 16,
        periodMs: 3200,
        phase: 1.6,
        label: 'PM',
      },
    ],
  }),
  lvl({
    id: 0,
    chapter: 'overtime',
    name: 'Standup Slot',
    tagline: 'A short meeting in the middle. The sides are still yours.',
    mechanics: ['Paddle'],
    start: { x: 70, y: 552 },
    goal: { x: 286, y: 78 },
    goalRadius: 26,
    maxBounces: 18,
    walls: [...bounds(), wall('agenda', 40, 200, 90, 14), wall('notes', 240, 420, 80, 14)],
    paddles: [
      {
        id: 'standup',
        x: 180,
        y: 320,
        length: 100,
        thickness: 16,
        periodMs: 2400,
        phase: 0.6,
        boost: 1.1,
        label: 'MTG',
      },
    ],
  }),
  lvl({
    id: 0,
    chapter: 'overtime',
    name: 'Night Desk',
    tagline: 'The desk belt slides you toward a late elevator.',
    mechanics: ['Walkway', 'Elevator'],
    start: { x: 70, y: 540 },
    goal: { x: 292, y: 68 },
    maxBounces: 16,
    walls: [
      ...bounds(),
      wall('bullpen', 16, 16, 220, 450),
      wall('night-l', 248, 16, 16, 450),
      wall('night-r', 328, 16, 16, 560),
    ],
    zones: [
      {
        id: 'night-belt',
        kind: 'belt',
        x: 24,
        y: 490,
        w: 220,
        h: 110,
        dir: { x: 1, y: 0 },
        speed: 400,
        label: 'DESK',
      },
      {
        id: 'night-up',
        kind: 'shaft',
        x: 264,
        y: 32,
        w: 64,
        h: 540,
        speed: 660,
        label: 'ELEV',
      },
    ],
  }),
  lvl({
    id: 0,
    chapter: 'overtime',
    name: 'Agenda Item',
    tagline: 'One more spinning bar, parked off the main aisle.',
    mechanics: ['Paddle', 'Boost pad'],
    start: { x: 180, y: 556 },
    goal: { x: 180, y: 74 },
    goalRadius: 26,
    maxBounces: 18,
    walls: [
      ...bounds(),
      wall('boost-aisle', 40, 470, 70, 16, { kind: 'pad', boost: 1.36, label: 'BOOST' }),
      ...shelf('item', 190, 120, 120),
    ],
    paddles: [
      {
        id: 'item',
        x: 286,
        y: 340,
        length: 90,
        thickness: 14,
        periodMs: 2800,
        phase: 1.2,
        label: 'MTG',
      },
    ],
  }),
  lvl({
    id: 13,
    chapter: 'boss',
    name: 'ASAP ASAP',
    tagline: 'Boss pings shove. Your aim gets the last word.',
    mechanics: ['Boss pings'],
    start: { x: 64, y: 548 },
    goal: { x: 292, y: 92 },
    goalRadius: 24,
    maxBounces: 16,
    walls: [
      ...bounds(),
      wall('shelf-a', 48, 210, 150, 16),
      wall('shelf-b', 170, 360, 150, 16),
      wall('pillar', 160, 430, 20, 90),
    ],
    distractors: [
      ping('p1', 'Boss: quick sync?', 550, { x: 120, y: -30 }, 70, 130),
      ping('p2', 'ASAP — no rush (rush)', 1500, { x: -110, y: 50 }, 180, 250),
      ping('p3', 'Per my last ping', 2500, { x: 80, y: -90 }, 60, 430),
    ],
  }),
  lvl({
    id: 14,
    chapter: 'boss',
    name: 'CC: Everyone',
    tagline: 'Reply-all yanks you back across the floor. Bank it.',
    mechanics: ['CC pad'],
    start: { x: 64, y: 430 },
    goal: { x: 72, y: 86 },
    goalRadius: 26,
    maxBounces: 18,
    walls: [
      ...bounds(),
      wall('lid-l', 16, 196, 108, 18),
      wall('lid-r', 196, 196, 148, 18),
      wall('cc-floor', 200, 528, 110, 18, { kind: 'reverse', boost: 1.24, label: 'CC' }),
      wall('cc-bank', 250, 340, 78, 16, { kind: 'reverse', boost: 1.16, label: 'CC' }),
    ],
  }),
  lvl({
    id: 15,
    chapter: 'boss',
    name: 'Performance Review',
    tagline: 'The red stamp means revise the angle. Max is fine.',
    mechanics: ['CC pad', 'Review trap'],
    start: { x: 64, y: 545 },
    goal: { x: 290, y: 100 },
    goalRadius: 24,
    maxBounces: 16,
    walls: [
      ...bounds(),
      wall('review', 150, 300, 64, 20, { kind: 'hazard', label: 'REVIEW' }),
      wall('cc', 240, 480, 80, 18, { kind: 'reverse', boost: 1.2, label: 'CC' }),
      wall('file', 36, 200, 120, 16),
    ],
    distractors: [ping('p1', 'Can you hop on for a sec', 700, { x: 100, y: -40 }, 80, 140)],
  }),
  lvl({
    id: 0,
    chapter: 'boss',
    name: 'One More Thing',
    tagline: 'A single ping. Your line to the capsule still holds.',
    mechanics: ['Boss pings'],
    start: { x: 70, y: 540 },
    goal: { x: 286, y: 86 },
    maxBounces: 14,
    walls: [
      ...bounds(),
      wall('thread', 48, 240, 140, 16),
      wall('reply', 190, 400, 130, 16),
    ],
    distractors: [ping('once', 'Boss: one small favor', 800, { x: 90, y: -20 }, 90, 160)],
  }),
  lvl({
    id: 0,
    chapter: 'boss',
    name: 'Reply All',
    tagline: 'The CC pad is optional. The open side is kinder.',
    mechanics: ['CC pad'],
    start: { x: 80, y: 540 },
    goal: { x: 280, y: 90 },
    maxBounces: 16,
    walls: [
      ...bounds(),
      wall('cc-side', 40, 460, 70, 16, { kind: 'reverse', boost: 1.16, label: 'CC' }),
      wall('thread-wall', 160, 200, 16, 180),
      wall('header', 200, 340, 120, 16),
    ],
  }),
  lvl({
    id: 0,
    chapter: 'boss',
    name: 'Red Stamp',
    tagline: 'The stamp sits in the corner. Revise around it.',
    mechanics: ['Review trap', 'Boost pad'],
    start: { x: 70, y: 548 },
    goal: { x: 286, y: 84 },
    maxBounces: 16,
    walls: [
      ...bounds(),
      wall('stamp', 24, 250, 56, 18, { kind: 'hazard', label: 'REVIEW' }),
      wall('boost-out', 200, 450, 78, 16, { kind: 'pad', boost: 1.38, label: 'BOOST' }),
      wall('memo', 120, 180, 140, 16),
    ],
  }),
  lvl({
    id: 16,
    chapter: 'finale',
    name: 'Last Train Home',
    tagline: 'Platform belt, closing doors, then the safe car elevator.',
    mechanics: ['Doors', 'Walkway', 'Elevator'],
    start: { x: 72, y: 560 },
    goal: { x: 294, y: 64 },
    maxBounces: 20,
    walls: [
      ...bounds(),
      wall('station', 16, 16, 220, 490),
      wall('shaft-l', 236, 16, 16, 490),
      wall('shaft-r', 328, 16, 16, 580),
      ...doorPair('car', 250, 252, 76, 2800, 200),
    ],
    zones: [
      {
        id: 'platform',
        kind: 'belt',
        x: 24,
        y: 508,
        w: 220,
        h: 100,
        dir: { x: 1, y: 0 },
        speed: 440,
        label: 'WALK',
      },
      {
        id: 'car',
        kind: 'shaft',
        x: 252,
        y: 36,
        w: 76,
        h: 560,
        speed: 680,
        label: 'ELEV',
      },
    ],
  }),
  lvl({
    id: 17,
    chapter: 'finale',
    name: 'Night Transfer',
    tagline: 'Slick platform, a spinning board, an open door if you wait.',
    mechanics: ['Doors', 'Slick', 'Paddle'],
    start: { x: 180, y: 568 },
    goal: { x: 180, y: 74 },
    goalRadius: 26,
    maxBounces: 20,
    walls: [
      ...bounds(),
      ...lintel('transfer', 360, 128, 104),
      ...doorPair('transfer', 360, 128, 104, 2600, 0),
    ],
    zones: [
      {
        id: 'wet',
        kind: 'slick',
        x: 40,
        y: 420,
        w: 280,
        h: 150,
        label: 'COFFEE',
      },
    ],
    paddles: [
      {
        id: 'board',
        x: 262,
        y: 220,
        length: 116,
        thickness: 16,
        periodMs: 3000,
        phase: 0.8,
        boost: 1.1,
        label: 'MTG',
      },
    ],
  }),
  lvl({
    id: 18,
    chapter: 'finale',
    name: 'Platform Meds',
    tagline: 'Whole shift in one launch. The inbox survives until morning.',
    mechanics: ['Full shift'],
    start: { x: 70, y: 562 },
    goal: { x: 292, y: 62 },
    goalRadius: 24,
    maxBounces: 24,
    winTitle: 'Shift complete',
    winBody: 'You got the meds and the last train. The overtime clock can run without you tonight.',
    walls: [
      ...bounds(),
      wall('station', 16, 16, 200, 474),
      wall('shaft-l', 216, 16, 16, 474),
      wall('shaft-r', 328, 16, 16, 580),
      ...doorPair('last', 210, 232, 96, 3000, 250),
      wall('cc', 24, 508, 44, 18, { kind: 'reverse', boost: 1.14, label: 'CC' }),
      wall('review', 20, 590, 46, 14, { kind: 'hazard', label: 'REVIEW' }),
    ],
    zones: [
      {
        id: 'platform',
        kind: 'belt',
        x: 24,
        y: 512,
        w: 200,
        h: 96,
        dir: { x: 1, y: 0 },
        speed: 420,
        label: 'WALK',
      },
      {
        id: 'spill',
        kind: 'slick',
        x: 230,
        y: 470,
        w: 90,
        h: 130,
        label: 'COFFEE',
      },
      {
        id: 'home',
        kind: 'shaft',
        x: 232,
        y: 32,
        w: 96,
        h: 560,
        speed: 700,
        label: 'ELEV',
      },
    ],
    paddles: [
      {
        id: 'finale-mtg',
        x: 300,
        y: 400,
        length: 70,
        thickness: 14,
        periodMs: 2600,
        phase: 0.5,
        label: 'MTG',
      },
    ],
    distractors: [ping('last', 'Boss: one more thing', 900, { x: -60, y: -16 }, 70, 430)],
  }),
  lvl({
    id: 0,
    chapter: 'finale',
    name: 'Side Platform',
    tagline: 'Left-hand platform, a door, then the safe car.',
    mechanics: ['Doors', 'Walkway', 'Elevator'],
    start: { x: 292, y: 552 },
    goal: { x: 78, y: 68 },
    maxBounces: 18,
    walls: [
      ...bounds(),
      wall('side-station', 130, 16, 214, 470),
      wall('side-l', 16, 16, 16, 470),
      wall('side-r', 114, 16, 16, 470),
      ...doorPair('side', 240, 32, 82, 2800, 180),
    ],
    zones: [
      {
        id: 'side-walk',
        kind: 'belt',
        x: 140,
        y: 500,
        w: 190,
        h: 100,
        dir: { x: -1, y: 0 },
        speed: 420,
        label: 'WALK',
      },
      {
        id: 'side-car',
        kind: 'shaft',
        x: 32,
        y: 32,
        w: 82,
        h: 540,
        speed: 660,
        label: 'ELEV',
      },
    ],
  }),
  lvl({
    id: 0,
    chapter: 'finale',
    name: 'After Hours',
    tagline: 'Coffee, a boost, and a late ping. The capsule is still up there.',
    mechanics: ['Slick', 'Boost pad', 'Boss pings'],
    start: { x: 72, y: 548 },
    goal: { x: 286, y: 78 },
    goalRadius: 24,
    maxBounces: 18,
    walls: [
      ...bounds(),
      wall('late-pad', 40, 450, 76, 16, { kind: 'pad', boost: 1.4, label: 'BOOST' }),
      wall('late-desk', 150, 240, 16, 140),
      wall('late-shelf', 200, 160, 120, 16),
    ],
    zones: [
      {
        id: 'late-spill',
        kind: 'slick',
        x: 30,
        y: 480,
        w: 220,
        h: 110,
        label: 'COFFEE',
      },
    ],
    distractors: [ping('late', 'Boss: still there?', 700, { x: 70, y: -24 }, 80, 200)],
  }),
  lvl({
    id: 0,
    chapter: 'finale',
    name: 'Capsule Call',
    tagline: 'Last call. Belt, door, elevator, then the capsule.',
    mechanics: ['Full shift'],
    start: { x: 64, y: 556 },
    goal: { x: 292, y: 66 },
    goalRadius: 24,
    maxBounces: 22,
    winTitle: 'Capsule in hand',
    winBody: 'The shift can end. Max has his meds, and the train is still his.',
    walls: [
      ...bounds(),
      wall('call-block', 16, 16, 210, 460),
      wall('call-l', 240, 16, 16, 460),
      wall('call-r', 328, 16, 16, 560),
      ...doorPair('call', 220, 256, 72, 2800, 220),
      wall('call-cc', 28, 500, 48, 16, { kind: 'reverse', boost: 1.12, label: 'CC' }),
    ],
    zones: [
      {
        id: 'call-walk',
        kind: 'belt',
        x: 24,
        y: 508,
        w: 200,
        h: 90,
        dir: { x: 1, y: 0 },
        speed: 400,
        label: 'WALK',
      },
      {
        id: 'call-up',
        kind: 'shaft',
        x: 256,
        y: 32,
        w: 72,
        h: 540,
        speed: 680,
        label: 'ELEV',
      },
    ],
    paddles: [
      {
        id: 'call-mtg',
        x: 120,
        y: 300,
        length: 80,
        thickness: 14,
        periodMs: 3000,
        phase: 0.4,
        label: 'MTG',
      },
    ],
  }),
];

export const LEVELS: LevelDef[] = CAMPAIGN.map((level, index) => ({ ...level, id: index + 1 }));

export function getLevel(id: number): LevelDef | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function levelCount() {
  return LEVELS.length;
}
